set shell := ["sh", "-c"]
set windows-shell := ["powershell", "-c"]

_main:
    @just --list
    
test:
    cargo test  --target aarch64-unknown-linux-gnu -- --no-capture

build:
    cargo build --target aarch64-unknown-linux-gnu

